version: '3.7'

services:

    mysql-database:
        image: mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        container_name: standalone_mysql
        working_dir: /docker-entrypoint-initdb.d
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: forest_mysql
          MYSQL_USER: forest
          MYSQL_PASSWORD: secret
        ports:
            - 3306:3306
        volumes:
            - .:/docker-entrypoint-initdb.d
